sudo: required
services:
- docker
env:
  global:
  - IMAGE_NAME=gtesei/hello_docker_2
  - REGISTRY_USER=gtesei
  - secure: IZoBp6aFwnDCAfGkdcEGOZcl+2Fgc1+arhSYaN5ISTVSQqZoYhN/TjXg7bGsZcUUduePSxWGAOFErWlToBoRMcPbh5dmzrXVaD1si82xy87OrG6fIEF95LXFBTYFQ8uhBagSpZx/u1rW63rlZqLmnHKoNGWfriQrmgTAPigy8zCHAE3QQPrDbauFeFnKHoUNMpZrp6h/RaFhhsfx5eqLQRNS9UaDiC/EgtDe4U7U0BKm0VJ+2nsli/oxYRTIe1upA4wbB3jq91kKEx2AH7QWEwcfeFt/iEPjzU1XxY1ikbb3W/tVSMKwWtuYiebdf998b+mSCqJuVR1FQHQnZizsASgIFJN9+QYgY9BYMY4q0KxtyZeG0hUVbwGKZf5p4/ROwa9cQpf8X1kSm+etijcPZzzwdc4xgLlz29r2qU6WieBJWFeyGKqdlOMO0963VnIeqx0vWbeqCiN5RJt6BGYQPZgm68sjCOOxOtzJ4pRj5UmzCB6yJTs/KhyHoJsDavlhlncERykC3pzFykJ+M2xl0dNfRHjykTgaX/SrPxAmXUU4Sr5zO9LaVcpDi4Ysd+vkJkeZ0KMz4BJkqfXUNI8CEiZ3KjqIeJLsjaH0tqiz6cSFIBYVsRrAeHwyGJkJtmX1mU9aZUugAMhOBVj47SIRrKIyXU9l+59lw/AxjoXl4cw=
before_script:
- version="$(sed -nE 's/^blog-travis-docker==(\S+).*/\1/p' requirements.txt)"
- docker pull "$IMAGE_NAME" || true
script:
- docker build --pull --cache-from "$IMAGE_NAME" --tag "$IMAGE_NAME" .
- docker run "$IMAGE_NAME"
after_script:
- docker images
before_deploy:
- docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
- docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
- docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${version}"
deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${version}"
  on:
    branch: master
